from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
INPUT_DIR = BASE_DIR / "input"
OUTPUT_DIR = BASE_DIR / "output"

RAW_EVENT_CSV = INPUT_DIR / "gemini_24h_analysis.csv"

SCHEMA_SUMMARY_JSON = OUTPUT_DIR / "schema_summary.json"
METRICS_CSV = OUTPUT_DIR / "strategy_metrics.csv"
STATE_TIMESERIES_CSV = OUTPUT_DIR / "state_timeseries.csv"
FILL_LOG_CSV = OUTPUT_DIR / "fill_log.csv"
QUOTE_LOG_CSV = OUTPUT_DIR / "quote_log.csv"
PNL_PNG = OUTPUT_DIR / "cumulative_pnl.png"
INVENTORY_PNG = OUTPUT_DIR / "inventory_path.png"
DRAWDOWN_PNG = OUTPUT_DIR / "drawdown.png"
FILL_ACTIVITY_PNG = OUTPUT_DIR / "fill_activity.png"

# Loader and data hygiene
MAX_EVENTS = 1_000_000
REPORT_EVERY_N_EVENTS = 100_000
MIN_VALID_PRICE = 1_000.0
MAX_VALID_PRICE = 2_000_000.0
MIN_VALID_AMOUNT = 1e-8
MAX_VALID_AMOUNT = 1_000.0
PRICE_TICK = 0.01

# Logging cadence
STATE_LOG_INTERVAL_MS = 1_000
QUOTE_REFRESH_MS = 500

# Strategy parameters
MAKER_FEE_RATE = 0.0005
LIQUIDATION_FEE_RATE = 0.0005
INITIAL_CASH = 20_000.0
BASE_ORDER_SIZE = 0.01
MIN_ORDER_SIZE = 0.001
MAX_INVENTORY = 0.15
INVENTORY_TARGET = 0.0
INVENTORY_SKEW_TICKS = 8.0
INVENTORY_SOFT_LIMIT_FRACTION = 0.75
SIZE_SKEW_FACTOR = 0.75

MICROPRICE_WEIGHT = 0.7
IMBALANCE_ALPHA_BPS = 6.0
TRADE_FLOW_ALPHA_BPS = 4.0
BOOK_FLOW_ALPHA_BPS = 2.0
ALPHA_CLIP_BPS = 12.0

MIN_HALF_SPREAD_TICKS = 2.0
MARKET_SPREAD_MULTIPLIER = 1.25
VOLATILITY_SPREAD_MULTIPLIER = 2.0
FLOW_SPREAD_MULTIPLIER = 0.35
INVENTORY_SPREAD_MULTIPLIER = 0.75

# Opportunity gating
MIN_REQUIRED_EDGE_BUFFER_BPS = 1.0
MAX_VOLATILITY_TO_QUOTE_BPS = 20.0
MAX_FLOW_RATIO_TO_QUOTE = 0.08
MIN_DIRECTIONAL_ALPHA_BPS = 1.0
ALLOW_TWO_SIDED_WHEN_ALPHA_SMALL = True

# Quote persistence / inventory unwind
QUOTE_REPRICE_THRESHOLD_TICKS = 2.0
QUOTE_MAX_AGE_MS = 3_000
INVENTORY_UNWIND_THRESHOLD_FRACTION = 0.01
INVENTORY_UNWIND_JOIN_TOUCH = True
INVENTORY_UNWIND_SIZE_MULTIPLIER = 1.35
CALM_MARKET_VOL_THRESHOLD_BPS = 6.0
CALM_MARKET_SPREAD_THRESHOLD_BPS = 1.2
CALM_MARKET_TIGHTENING_FACTOR = 0.65

VOLATILITY_WINDOW_MS = 5_000
FLOW_WINDOW_MS = 5_000
BOOK_FLOW_WINDOW_MS = 5_000
LONG_VOL_WINDOW_MS = 60_000

# Fill model assumptions
TOUCH_FILL_FRACTION = 0.35
IMPROVED_PRICE_FILL_FRACTION = 0.85
MIN_FILL_SIZE = 1e-6
